name: Process tokens

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  process-tokens:
    name: Process tokens
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code from GitHub
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Transform the tokens
      run: |
        npm ci
        npm run build

    - name: Save transformed tokens as artifact
      uses: actions/upload-artifact@v2
      with:
        name: tokens
        path: tokens/

    - name: Publish to NPM
        # git config user.email "travis@microsoft.com"
        # git config user.name "GitHub Actions bot"
        # git push
        # git push --tags
      run: |
        npm version --no-git-tag-version major
        npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Rename HTML for GitHub Pages
      run: mv tokens/reference/fluentuitokens.html tokens/reference/index.html

    - name: Deploy HTML to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: tokens/reference
